### ISSUE TITLE
Exception decoding artifacts.json due to null field

### ISSUE THREAD

**Issue by gqmulligan** [usefulness/licensee-for-android#73]
When code generation is enabled an exception is thrown when a project references a library with incomplete license information (invalid SPDX identifier and no url).
An example is the MSAL library from Microsoft. Licensee produces the following JSON for the `com.microsoft.identity.client:msal` dependency:
```
  {
      "groupId": "com.microsoft.identity.client",
      "artifactId": "msal",
      "version": "4.0.1",
      "name": "msal",
      "unknownLicenses": [
          {
              "name": "MIT License",
              "url": null
          }
      ],
      "scm": {
          "url": "https://github.com/AzureAD/microsoft-authentication-library-for-android/tree/master"
      }
  }
```

The `"url": null` on the `UnknownLicense` causes the following exception when the plugin runs:

> kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1030: Expected string literal but 'null' literal was found at path: $[101].unknownLicenses[0].url
> Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values.

`name` and `url` are both nullable in `Licensee` and they should be here too, or else specify defaults as mentioned in the error message.

Thanks for the great plugin!

**Comment by mateuszkwiecinski** [comment]
Thanks for the report! You're absolutely right: the fields should be nullable. 
I just pulished `0.2.2` which should have the issue resolved 🤞 Happy coding!
